"""Trophy definitions — shared between computation and display layers."""

TROPHY_DEFS: list[dict] = [
    # ── Tiered ───────────────────────────────────────────────────────────
    {
        "id": "forge_master",
        "name": "Forge Master",
        "icon": "flame",
        "tui_icon": "🔥",
        "flat": False,
        "color": "hearth",
        "desc": "Deep work — focused pomos completed today",
        "tiers": {
            "bronze": "2 pomos",
            "silver": "6 pomos",
            "gold":   "10 pomos",
        },
        "pr_label": "Most pomos in a day",
    },
    {
        "id": "frog_slayer",
        "name": "Frog Slayer",
        "icon": "target",
        "tui_icon": "🐸",
        "flat": False,
        "color": "hearth",
        "desc": "Eat your most dreaded task — bonus for doing it first",
        "tiers": {
            "bronze": "Frog eaten",
            "silver": "Eaten before noon",
            "gold":   "Eaten as first quest",
        },
        "pr_label": "Earliest frog completion",
    },
    # ── Flat unlocks ─────────────────────────────────────────────────────
    {
        "id": "dawn_forge",
        "name": "Dawn Forge",
        "icon": "hourglass",
        "tui_icon": "🌅",
        "flat": True,
        "color": "secondary",
        "desc": "First pomo before 9am — ignite the day early",
        "pr_label": "Earned",
    },
    {
        "id": "berserker",
        "name": "Berserker",
        "icon": "zap",
        "tui_icon": "⚡",
        "flat": True,
        "color": "secondary",
        "desc": "Pushed past the timer — entered deep flow",
        "pr_label": "Earned",
    },
    {
        "id": "ghost_mode",
        "name": "Ghost Mode",
        "icon": "shield",
        "tui_icon": "👻",
        "flat": True,
        "color": "primary",
        "desc": "Zero interruptions across every pomo today",
        "pr_label": "Earned",
    },
    {
        "id": "deep_siege",
        "name": "Deep Siege",
        "icon": "sword",
        "tui_icon": "⚔️",
        "flat": True,
        "color": "primary",
        "desc": "4+ pomos on one quest — obsessive focus",
        "pr_label": "Earned",
    },
    {
        "id": "sabbath",
        "name": "Sabbath",
        "icon": "moon",
        "tui_icon": "🌙",
        "flat": True,
        "color": "tertiary",
        "desc": "Took a long break — recovery is part of the fight",
        "pr_label": "Earned",
    },
    {
        "id": "zero_debt",
        "name": "Zero Debt",
        "icon": "check-circle",
        "tui_icon": "⚖️",
        "flat": True,
        "color": "tertiary",
        "desc": "Closed at least as many quests as you opened today",
        "pr_label": "Earned",
    },
]
