"""Trophy definitions — shared between computation and display layers."""

TROPHY_DEFS: list[dict] = [
    # ── Tiered ───────────────────────────────────────────────────────────
    {
        "id": "forge_master",
        "name": "Forge Master",
        "icon": "flame",
        "tui_icon": "🔥",
        "flat": False,
        "color": "hearth",
        "desc": "Deep work — focused pomos completed today",
        "tiers": {
            "bronze": "2 pomos",
            "silver": "6 pomos",
            "gold":   "10 pomos",
        },
        "pr_label": "Most pomos in a day",
    },
    {
        "id": "frog_slayer",
        "name": "Frog Slayer",
        "icon": "target",
        "tui_icon": "🐸",
        "flat": False,
        "color": "hearth",
        "desc": "Eat your most dreaded task — bonus for doing it first",
        "tiers": {
            "bronze": "Frog eaten",
            "silver": "Eaten before noon",
            "gold":   "Eaten as first quest",
        },
        "pr_label": "Earliest frog completion",
    },
    {
        "id": "doomfire_slayer",
        "name": "Doomfire Slayer",
        "icon": "flame",
        "tui_icon": "🔥",
        "flat": False,
        "color": "hearth",
        "desc": "Conquer P0 Doomfire quests before they consume the board",
        "tiers": {
            "bronze": "1 P0 quest",
            "silver": "2 P0 quests",
            "gold":   "3 P0 quests",
        },
        "pr_label": "Most P0 quests in a day",
    },
    # ── Flat unlocks ─────────────────────────────────────────────────────
    {
        "id": "dawn_forge",
        "name": "Dawn Forge",
        "icon": "hourglass",
        "tui_icon": "🌅",
        "flat": True,
        "color": "secondary",
        "desc": "First pomo before 9am — ignite the day early",
        "pr_label": "Earned",
    },
    {
        "id": "berserker",
        "name": "Berserker",
        "icon": "zap",
        "tui_icon": "⚡",
        "flat": True,
        "color": "secondary",
        "desc": "Pushed past the timer — entered deep flow",
        "pr_label": "Earned",
    },
    {
        "id": "ghost_mode",
        "name": "Ghost Mode",
        "icon": "shield",
        "tui_icon": "👻",
        "flat": True,
        "color": "primary",
        "desc": "Zero interruptions across every pomo today",
        "pr_label": "Earned",
    },
    {
        "id": "deep_siege",
        "name": "Deep Siege",
        "icon": "sword",
        "tui_icon": "⚔️",
        "flat": True,
        "color": "primary",
        "desc": "4+ pomos on one quest — obsessive focus",
        "pr_label": "Earned",
    },
    {
        "id": "sabbath",
        "name": "Sabbath",
        "icon": "moon",
        "tui_icon": "🌙",
        "flat": True,
        "color": "tertiary",
        "desc": "Took a long break — recovery is part of the fight",
        "pr_label": "Earned",
    },
    {
        "id": "zero_debt",
        "name": "Zero Debt",
        "icon": "check-circle",
        "tui_icon": "⚖️",
        "flat": True,
        "color": "tertiary",
        "desc": "Closed at least as many quests as you opened today",
        "pr_label": "Earned",
    },
    {
        "id": "ancient_bane",
        "name": "Ancient Bane",
        "icon": "hourglass",
        "tui_icon": "⌛",
        "flat": True,
        "color": "secondary",
        "desc": "Completed an ancient or fossil quest today",
        "pr_label": "Earned",
    },
    {
        "id": "first_strike",
        "name": "First Strike",
        "icon": "target",
        "tui_icon": "🎯",
        "flat": True,
        "color": "primary",
        "desc": "First completed quest today was P0 or P1",
        "pr_label": "Earned",
    },
    {
        "id": "triage_rite",
        "name": "Triage Rite",
        "icon": "shield",
        "tui_icon": "🛡",
        "flat": True,
        "color": "tertiary",
        "desc": "All open P0/P1 quests are fresh or aging",
        "pr_label": "Earned",
    },
    {
        "id": "deep_priority",
        "name": "Deep Priority",
        "icon": "sword",
        "tui_icon": "⚔",
        "flat": True,
        "color": "primary",
        "desc": "Completed 2+ pomos on P0/P1 quests today",
        "pr_label": "Earned",
    },
]
