"""Repository protocols for QuestLog storage backends.

Both JSON and SQLite backends implement these interfaces, ensuring
core business logic works identically against either storage layer.
"""

from __future__ import annotations

from typing import Protocol


class QuestRepo(Protocol):
    def load_all(self, workspace_id: str = "work") -> list[dict]: ...
    def add(
        self,
        title: str,
        *,
        priority: int = 4,
        project: str | None = None,
        labels: list[str] | None = None,
        artifacts: dict | None = None,
        workspace_id: str = "work",
    ) -> dict: ...
    def update_status(self, quest_id: str, status: str, workspace_id: str = "work") -> dict | None: ...
    def abandon(self, quest_id: str, workspace_id: str = "work") -> dict | None: ...
    def toggle_frog(self, quest_id: str, workspace_id: str = "work") -> dict | None: ...
    def update_checklist(
        self, quest_id: str, checklist: list[dict], workspace_id: str = "work"
    ) -> dict | None: ...
    def update_priority(self, quest_id: str, priority: int, workspace_id: str = "work") -> dict | None: ...
    def update_project(
        self, quest_id: str, project: str | None, workspace_id: str = "work"
    ) -> dict | None: ...
    def update_labels(self, quest_id: str, labels: list[str], workspace_id: str = "work") -> dict | None: ...
    def update_artifacts(self, quest_id: str, artifacts: dict, workspace_id: str = "work") -> dict | None: ...


class WorkspaceRepo(Protocol):
    def list_workspaces(self) -> list[dict]: ...
    def get(self, workspace_id: str) -> dict | None: ...
    def create(self, name: str, icon: str, color: str) -> dict: ...


class ArtifactKeyRepo(Protocol):
    def list_keys(self) -> list[dict]: ...
    def add_key(self, name: str, icon: str | None = None) -> dict: ...
    def rename_key(self, old: str, new: str) -> None: ...
    def delete_key(self, name: str) -> None: ...
    def reorder(self, names_in_order: list[str]) -> None: ...


class PomoRepo(Protocol):
    def load_all(self, workspace_id: str = "work") -> list[dict]: ...
    def start_session(self, quest_id: str, quest_title: str, workspace_id: str = "work") -> dict: ...
    def get_session(self, session_id: str) -> dict | None: ...
    def add_segment(
        self,
        session_id: str,
        seg_type: str,
        lap: int,
        cycle: int,
        completed: bool,
        interruptions: int,
        started_at: str,
        ended_at: str,
        charge: str | None = None,
        deed: str | None = None,
        break_size: str | None = None,
        interruption_reason: str | None = None,
        early_completion: bool = False,
        forge_type: str | None = None,
    ) -> dict | None: ...
    def update_segment_deed(
        self, session_id: str, lap: int, deed: str,
        forge_type: str | None = None,
    ) -> None: ...
    def end_session(self, session_id: str) -> dict | None: ...


class TrophyPRRepo(Protocol):
    def load_prs(self) -> dict: ...
    def save_prs(self, prs: dict) -> None: ...


class ChallengeRepo(Protocol):
    async def create(self, era_name: str, start_date: str, midweek_adjective: str) -> dict: ...
    async def get_active(self) -> dict | None: ...
    async def get_by_id(self, challenge_id: str) -> dict | None: ...
    async def get_by_start_date(self, start_date: str) -> dict | None: ...
    async def update_level(self, challenge_id: str, level: int, level_name: str) -> None: ...
    async def update_days(self, challenge_id: str, days_elapsed: int) -> None: ...
    async def update_peak_level(self, challenge_id: str, peak: int) -> None: ...
    async def mark_completed(self, challenge_id: str) -> None: ...
    async def mark_reset(self, challenge_id: str) -> None: ...


class ChallengeTaskRepo(Protocol):
    async def create_batch(self, challenge_id: str, tasks: list[dict]) -> list[dict]: ...
    async def get_by_challenge(self, challenge_id: str) -> list[dict]: ...
    async def get_by_id(self, task_id: str) -> dict | None: ...


class ChallengeEntryRepo(Protocol):
    async def upsert(self, task_id: str, challenge_id: str, log_date: str,
                     state: str | None, notes: str | None) -> dict: ...
    async def get_by_date(self, challenge_id: str, log_date: str) -> list[dict]: ...
    async def get_last_n_for_task(self, task_id: str, n: int) -> list[dict]: ...
    async def get_all_for_task(self, task_id: str) -> list[dict]: ...
    async def get_all_for_challenge(self, challenge_id: str) -> list[dict]: ...
    async def mark_fail_triggered(self, entry_id: str, is_hard: bool) -> None: ...


class ChallengeEraRepo(Protocol):
    async def create(self, era_name: str, start_date: str, end_date: str,
                     duration_days: int, peak_level: int, reset_cause: str,
                     reset_trigger_task_id: str | None, summary_prose: str) -> dict: ...
    async def get_all(self) -> list[dict]: ...
    async def used_names(self) -> set[str]: ...


class ChallengeExperimentRepo(Protocol):
    async def create(self, challenge_id: str, action: str, motivation: str, timeframe: str) -> dict: ...
    async def get_by_id(self, experiment_id: str) -> dict | None: ...
    async def get_all(self) -> list[dict]: ...
    async def get_for_today(self, log_date: str) -> list[dict]: ...
    async def running_count(self, as_of: str | None = None) -> int: ...
    async def start(self, experiment_id: str, start_date: str) -> dict | None: ...
    async def judge(
        self,
        experiment_id: str,
        verdict: str,
        observation_notes: str | None,
        conclusion_notes: str | None,
    ) -> dict | None: ...
    async def abandon(self, experiment_id: str, reason: str = "") -> dict | None: ...
    async def extend(self, experiment_id: str, extra_days: int) -> dict | None: ...
    async def trash_draft(self, experiment_id: str) -> bool: ...
    async def upsert_entry(
        self,
        experiment_id: str,
        challenge_id: str,
        log_date: str,
        state: str | None,
        notes: str | None,
    ) -> dict: ...
    async def get_entries(self, experiment_id: str) -> list[dict]: ...
    async def get_entries_for_experiment(self, experiment_id: str) -> list[dict]: ...
    async def get_all_entries(self) -> list[dict]: ...
